steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}:${_IMAGE_TAG}",
        ".",
      ]
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}"
    ]

images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}"

options:
  logging: CLOUD_LOGGING_ONLY
