name: build

on:
  push:
    tags:
      - '*'
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  install_deps:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-go@v3
        name: setup golang
        with:
          go-version: '1.16'

      - run: make install
        name: install golang dependencies

  binary_build:
    needs:
      - install_deps
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-go@v3
        name: setup golang
        with:
          go-version: '1.16'

      - run: make build
        name: build golang binary file
