name: docker build

on:
  workflow_dispatch:
    workflows: ["main pipeline"]
    types: 
      - completed
    inputs:
      stage:
        description: 'stage to deploy'
        required: true
        default: 'dev-id'
        type: choice
        options:
        - dev-id
        - dev-sg

jobs:
  image_push:
    name: push image
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Service Stage: $SERVICE_STAGE"
        env:
          SERVICE_STAGE: ${{ inputs.stage }}
