name: deploy prod

on:
  workflow_dispatch:
    tags:
      - '**'
    inputs:
      stage:
        description: 'stage to deploy'
        required: true
        default: 'prod-id'
        type: choice
        options:
          - prod-id
          - prod-sg
      tag:
        description: 'image tag'
        required: true
        type: string

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

jobs:
  image_push:
    name: push image
    runs-on: ubuntu-latest
    env:
      SERVICE_STAGE: ${{ inputs.stage }}
      IMAGE_TAG: ${{ inputs.tag }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: build docker image
        run: make build-image

      - name: push docker image
        run: make push-image
