name: deploy prod

on:
  workflow_dispatch:
    branches:
      - 'master'
    tags:
      - '*'
    inputs:
      stage:
        description: 'stage to deploy'
        required: true
        default: 'prod-id'
        type: choice
        options:
          - prod-id
          - prod-sg

jobs:
  image_push:
    name: push image
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Service Stage: $SERVICE_STAGE"
        env:
          SERVICE_STAGE: ${{ inputs.stage }}
