name: deploy dev

on:
  workflow_dispatch:
    branches:
      - 'master'
      - 'feat/*'
      - 'fix/*'
      - 'ref/*'
    inputs:
      stage:
        description: 'stage to deploy'
        required: true
        default: 'dev-id'
        type: choice
        options:
          - dev-id
          - dev-sg

jobs:
  image_push:
    name: push image
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 'hello-gcp-367807'
      SERVICE_NAME: 'order-service'
      SERVICE_STAGE: ${{ inputs.stage }}
      IMAGE_TAG: ${{ inputs.tag }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set dev tag
        run: |
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: login gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: build docker image
        run: make build-image-dev

      - name: push docker image
        run: make push-image-dev
